# DataTypes & Attributes

In [16]:
import numpy as np

In [17]:
# NumPy's main datatype is ndarray
# n-dimensional array

# vector
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [18]:
type(a1)

numpy.ndarray

In [19]:
# matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array with depth of 2
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [20]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
a3.shape

(2, 3, 3)

In [23]:
# 3-dimensional array with dept of '3'
a4 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 19]]])


In [24]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 19]]])

In [25]:
# row, columns, depth
a4.shape

(3, 2, 3)

In [26]:
# dimensions of the above arrays
a1.ndim, a2.ndim, a3.ndim, a4.ndim

(1, 2, 3, 3)

In [29]:
# number of items in array
a1.size, a2.size, a3.size, a4.size

(3, 6, 18, 18)

In [28]:
# types of elements in array
a1.dtype, a2.dtype,a3.dtype, a4.dtype

(dtype('int32'), dtype('float64'), dtype('int32'), dtype('int32'))

In [30]:
type(a1), type(a2), type(a3), type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a dataframe from a NumPy array

In [31]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [33]:
# only works on matrices

# Creating NumPy Arrays

### Automatic Creation

In [38]:
ones = np.ones((2,3), int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
zeros = np.zeros((3,3), int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
ones_three_d = np.ones((2,3,3), int)
ones_three_d

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [41]:
# start, stop, step
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

### Random Array Creation

In [42]:
# random array, type(low, high, size())
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[4, 1, 6, 1, 0],
       [6, 8, 5, 0, 6],
       [7, 9, 2, 5, 3]])

In [45]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.96067419, 0.19153692, 0.75372687],
       [0.09752803, 0.17970657, 0.62359848],
       [0.31542786, 0.4734048 , 0.11270552],
       [0.66338946, 0.80394333, 0.68245592],
       [0.38340043, 0.76274507, 0.34329229]])

In [46]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.94945516, 0.40900073, 0.0729255 ],
       [0.28034401, 0.00868137, 0.73216909],
       [0.44300646, 0.86938742, 0.55714384],
       [0.83106084, 0.19735521, 0.8011305 ],
       [0.48120728, 0.61831359, 0.33309168]])

In [47]:
# note: these are pseudo-random numbers

# NumPy Seed

### Controlling the Random Numbers

In [56]:
np.random.seed(0)
rand_array_4 = np.random.randint(10, size=(5, 3))
rand_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [60]:
np.random.seed(5)
rand_array_5 = np.random.random(size=(3, 5))
rand_array_5

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703]])

# Viewing Arrays / Matrices

### Showing Parts of Array

In [62]:
np.unique(rand_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [64]:
# view by index
a2[0,1]

2.0

In [65]:
a4[0,1,2]

6

In [66]:
a4[2]

array([[13, 14, 15],
       [16, 17, 19]])

In [67]:
# array slicing, return the first two of each part of the array
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [68]:
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])

## Array Slicing Defined

In [69]:
# four-dimensional array slicing
a5 = np.random.randint(10, size=(2, 3, 4, 5))
a5

array([[[[4, 6, 2, 9, 9],
         [9, 9, 1, 2, 7],
         [0, 5, 0, 0, 4],
         [4, 9, 3, 2, 4]],

        [[6, 9, 3, 3, 2],
         [1, 5, 7, 4, 3],
         [1, 7, 3, 1, 9],
         [5, 7, 0, 9, 6]],

        [[0, 5, 2, 8, 6],
         [8, 0, 5, 2, 0],
         [7, 7, 6, 0, 0],
         [8, 5, 5, 9, 6]]],


       [[[4, 5, 2, 8, 8],
         [1, 6, 3, 4, 1],
         [8, 0, 2, 2, 4],
         [1, 6, 3, 4, 3]],

        [[1, 4, 2, 3, 4],
         [9, 4, 0, 6, 6],
         [9, 2, 9, 3, 0],
         [8, 8, 9, 7, 4]],

        [[8, 6, 8, 0, 5],
         [3, 4, 0, 2, 2],
         [1, 1, 7, 1, 7],
         [2, 6, 3, 6, 8]]]])

In [70]:
# shape: works backwards from right to left
# 5 = number of elements in a row
# 4 = number of rows in a matrix
# 3 = number of matrices in a group
# 2 = number of groups in the array
a5.shape, a5.ndim

((2, 3, 4, 5), 4)

In [72]:
# return the first four numbers of each row of each inner matrix
a5[:, :, :, :4]

array([[[[4, 6, 2, 9],
         [9, 9, 1, 2],
         [0, 5, 0, 0],
         [4, 9, 3, 2]],

        [[6, 9, 3, 3],
         [1, 5, 7, 4],
         [1, 7, 3, 1],
         [5, 7, 0, 9]],

        [[0, 5, 2, 8],
         [8, 0, 5, 2],
         [7, 7, 6, 0],
         [8, 5, 5, 9]]],


       [[[4, 5, 2, 8],
         [1, 6, 3, 4],
         [8, 0, 2, 2],
         [1, 6, 3, 4]],

        [[1, 4, 2, 3],
         [9, 4, 0, 6],
         [9, 2, 9, 3],
         [8, 8, 9, 7]],

        [[8, 6, 8, 0],
         [3, 4, 0, 2],
         [1, 1, 7, 1],
         [2, 6, 3, 6]]]])

In [85]:
# return just the first rows of all matrices
a5[:, :, :1, :5]

array([[[[4, 6, 2, 9, 9]],

        [[6, 9, 3, 3, 2]],

        [[0, 5, 2, 8, 6]]],


       [[[4, 5, 2, 8, 8]],

        [[1, 4, 2, 3, 4]],

        [[8, 6, 8, 0, 5]]]])

In [93]:
# return the last row of each matrix
a5[:, :, 3:4, :5]

array([[[[4, 9, 3, 2, 4]],

        [[5, 7, 0, 9, 6]],

        [[8, 5, 5, 9, 6]]],


       [[[1, 6, 3, 4, 3]],

        [[8, 8, 9, 7, 4]],

        [[2, 6, 3, 6, 8]]]])

In [94]:
# return the fourth element of each 3rd row
a5[:, :, 2:3, 3:4 ]

array([[[[0]],

        [[1]],

        [[0]]],


       [[[2]],

        [[3]],

        [[1]]]])

In [95]:
# return the third element of the fourth row of matrices 
# only in the second set
a5[1:2, :, 2:3, 3:4 ]

array([[[[2]],

        [[3]],

        [[1]]]])

In [ ]:
# sytax:
# X:Y
# X = starting point, non-inclusive. leave blank to include all
# Y = ending point, inclusive. Leave blank to include all
