# Comparison Operators

In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 19]]])
a4 = np.random.randint(10, size=(2, 3, 4, 5))

b1 = np.random.randint(1, 10, size=(2,3,2))
b2 = np.random.randint(1, 10, size=(3,2,2))

massive = np.random.random(100000)

In [2]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [3]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [6]:
a1 < a2

array([[False, False,  True],
       [ True,  True,  True]])

In [7]:
bool_array = a1 == a2

In [8]:
bool_array.dtype, type(bool_array), bool_array

(dtype('bool'),
 numpy.ndarray,
 array([[ True,  True, False],
        [False, False, False]]))

# Sorting Arrays

In [9]:
r1 = np.random.randint(10, size=(3,5))
r1

array([[2, 1, 5, 4, 8],
       [0, 0, 2, 2, 7],
       [0, 3, 2, 3, 3]])

In [16]:
r2 = np.random.rand(3,5)
r2

array([[0.28830702, 0.35940123, 0.59462801, 0.92030634, 0.02230919],
       [0.38193287, 0.98483122, 0.31536152, 0.26090379, 0.4140894 ],
       [0.67865066, 0.76480633, 0.77369933, 0.29541082, 0.99258121]])

In [12]:
np.sort(r1)

array([[1, 2, 4, 5, 8],
       [0, 0, 2, 2, 7],
       [0, 2, 3, 3, 3]])

In [17]:
# which index has the highest value
# the result is an array of indecies
np.argsort(r2)

array([[4, 0, 1, 2, 3],
       [3, 2, 0, 4, 1],
       [3, 0, 1, 2, 4]], dtype=int64)

In [18]:
# minium number is at which index?
np.argmin(r2)

4

In [19]:
# what about the maximum?
np.argmax(r2)

14

In [26]:
# shows the index with the highest value at each COLUMN
np.argmax(r2, axis=0)

array([2, 1, 2, 0, 2], dtype=int64)

In [27]:
# same as above but now for ROW
np.argmax(r2, axis=1)

array([3, 1, 4], dtype=int64)

In [47]:
# show those maximums
r2[0,3],r2[1,1],r2[2,4]

(0.9203063388919394, 0.984831223929224, 0.9925812145087434)