# Dot Product
Takes two equal-length sequences of numbers (usually coordinate vectors), and returns a single number

In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 19]]])
a4 = np.random.randint(10, size=(2, 3, 4, 5))

b1 = np.random.randint(1, 10, size=(2,3,2))
b2 = np.random.randint(1, 10, size=(3,2,2))

massive = np.random.random(100000)

In [16]:
np.random.seed(0)
m1 = np.random.randint(10, size = (5, 3))
m2 = np.random.randint(10, size = (5, 3))
m1, m2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

Matrices must have appropriate alignment for dot product to work

In [17]:
m2 = m2.T
m2

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [20]:
m3 = np.dot(m1, m2)
m3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [21]:
m1.shape, m2.shape, m3.shape

((5, 3), (3, 5), (5, 5))

## Example: Nut-Butter

In [59]:
np.random.seed(0)
# number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

### Create weekly sales dataFrame

In [122]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon","Tues","Wed","Thu","Fri"],
                            columns=["Almond Butter","Peanut Butter",
                                     "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thu               4              6             12
Fri               1              6              7

In [123]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

### Create prices DataFrame

In [124]:
# add the 'reshape' method to give the list the correct dimensions
# see next cell
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Almond Butter","Peanut Butter",
                                     "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [136]:
prices.shape, butter_prices.shape

((3,), (1, 3))

> To do dot product, number of columns in first matrix must match number of rows in the second matrix

In [125]:
prices.shape, sales_amounts.T.shape

((3,), (3, 5))

In [126]:
# rows x columns
# prices = (1 x 3)
# sales_amounts = (5 x 3)
# sales_amounts.T = (3 x 5)
prices, sales_amounts, sales_amounts.T

(array([10,  8, 12]),
 array([[12, 15,  0],
        [ 3,  3,  7],
        [ 9, 19, 18],
        [ 4,  6, 12],
        [ 1,  6,  7]]),
 array([[12,  3,  9,  4,  1],
        [15,  3, 19,  6,  6],
        [ 0,  7, 18, 12,  7]]))

This and the next cell do the same thing. Order matters if not using 'transpose'

In [127]:
total_sales = np.dot(sales_amounts, prices)
total_sales

array([240, 138, 458, 232, 142])

In [128]:
total_sales = np.dot(prices, sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

### We can do the same opperation on the dataframes


In [129]:
# note the different syntax
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thu  Fri
Price  240   138  458  232  142

In [130]:
# using 'np.dot' results in just the values, not a new dataframe
daily_sales_alt = np.dot(butter_prices, weekly_sales.T)
daily_sales_alt

array([[240, 138, 458, 232, 142]])

In [134]:
# add the above data as a column in our dataframe for weekly_sales
weekly_sales_final = weekly_sales
weekly_sales_final["Total ($)"] = daily_sales.T
weekly_sales_final

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon              12             15              0        240
Tues              3              3              7        138
Wed               9             19             18        458
Thu               4              6             12        232
Fri               1              6              7        142